### ISSUE TITLE
Update ReadMe

### ISSUE THREAD

**Issue by acrosman** [acrosman/ElectronSimpleStarter#1]
The ReadMe file could use editing. In particular there are a few typos and the directions could use some clarification.

**Comment by Sahastracookcoder1** [comment]
Hi, acrosman!!

I would like to do this. Can you assign me to do the same?

**Comment by acrosman** [comment]
I don't usually bother with assignments for documentation updates like this one. I am happy to get two or three pull requests that all make various improvements and I don't mind if that means I have to do a little work to merge them later.

I had updated this to be a task for [Hacktoberfest](https://hacktoberfest.digitalocean.com/), which doesn't start for a couple days yet. If you are planning to participate in that event you might wait before working in this.

**Comment by Sahastracookcoder1** [comment]
Okay But assign me first for this.

**Comment by acrosman** [comment]
Like I said the documentation updates are just up for grabs. There is no really "finishing" them as they files can always be further improved. Please feel free to offer a PR, if I end up having to handle a merge between multiple good updates you will get credit for Hacktoberfest no matter how I resolve it.
